version: '3.8'
services:
  frontend:
    build: ../mern-app/client/ 
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ../mern-app/server/
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - ../mern-app/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=myNewDatabase
    networks:
      - mern-network

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://root:example@database:27017/admin?authMechanism=SCRAM-SHA-256
    ports:
      - "9216:9216"
    depends_on:
      - database
    networks:
      - mern-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - mern-network
    depends_on:
      - database
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - mern-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mern-network
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,ro'
    ports:
      - "9100:9100"
    networks:
      - mern-network

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  db-data:

networks:
  mern-network: